---
repo-name: peripherals-ms-sql
categories:
- Database
- Storage
display-name: MS SQL
manufacturer: Microsoft
description: Microsoft SQL Server is a relational database management system developed by Microsoft.
